### ISSUE TITLE
Gateway Time-Out

### ISSUE THREAD

**Issue by YunheeLee** [shlee322/delivery-tracker#138]
안녕하세요. 해당 API잘 사용중에 있습니다.
현재 사이트 CJ대한통운 API사용 시 Gateway Time Out 504가 뜨는데 봐주실 수 있을까요?
https://apis.tracker.delivery/carriers/kr.cjlogistics/tracks/647804595982

**Comment by YunheeLee** [comment]
> 안녕하세요. 해당 API잘 사용중에 있습니다. 현재 사이트 CJ대한통운 API사용 시 Gateway Time Out 504가 뜨는데 봐주실 수 있을까요?
https://apis.tracker.delivery/carriers/kr.cjlogistics/tracks/647804595982

**Comment by banana0117** [comment]
저도 api 요청시 문제가 발생하고있습니다 ㅠㅠ
항상 감사드립니다

**Comment by hmg11123** [comment]
저도 api 요청시 똑같은 문제가 발생되고 있습니다 ㅠㅠ
항상 고마워요

**Comment by gaeun9188** [comment]
안녕하세요, 저도 해당 API를 문제없이 잘 사용중에 있습니다.
하지만 4월 9일 부터 사이트 롯데택배 API 요청시 오류가 발생되고 있어 빠른 해결요청을 부탁드리려합니다.
교재구매를 구매한 연관 주문건들의 경우 취소/환불 및 배송관리에 문제가 있어 빠른 해결 부탁드립니다 ㅠㅠ

**Comment by shlee322** [comment]
오늘 중으로 확인해보도록 하겠습니다. 감사합니다.

**Comment by shlee322** [comment]
처리되었습니다. 리포트 감사합니다.
향후 누구나 볼 수 있는 서비스 상태 대시보드를 제공할 예정입니다.
감사합니다.

**Comment by gaeun9188** [comment]
[shlee322] 담당자님.
처리 완료되었다는 메일답변을 받고, 금일 배송조회를 동일하게 진행하였으나
문제가 해결되지 않아 재확인 부탁드리려 합니다 ㅠㅠ

**Comment by gaeun9188** [comment]
안녕하세요,

다름이 아니라 어제 커뮤니티 사이트(https://github.com/shlee322/delivery-tracker/issues/138)에서
오류 확인요청 후 처리완료되었다는 메일 및 답변을 받았으나
동일한 오류현상이 계속되고 있어 재확인 요청 드리려 합니다 ㅠㅠㅠ

처리 완료되었다는 메일 받고 확인했을때는 정상적으로 팝업이 노출된 내용을 확인하였으나
금일 출근 후 재확인시 어제와 같은 오류가 동일하게 발생되고 있네요...
교재 결제취소 등과도 연관되어있어 빠른 확인요청드리는 점 양해부탁드립니다 ㅠㅠ

감사합니다.



--- Original Message ---
From : "Vint Sanghyeok ***@***.***>
To : ***@***.***>
Cc : ***@***.***>, ***@***.***>
Date : 2022/04/13 수요일 오후 6:22:27
Subject : Re: [shlee322/delivery-tracker] Gateway Time-Out (Issue #138)


처리되었습니다. 리포트 감사합니다.
향후 누구나 볼 수 있는 서비스 상태 대시보드를 제공할 예정입니다.
감사합니다.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/shlee322/delivery-tracker/issues/138#issuecomment-1097784561", "url": "https://github.com/shlee322/delivery-tracker/issues/138#issuecomment-1097784561", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by gaeun9188** [comment]
ㅠㅠ 오늘 중으로 오류 재확인이 가능할지 요청드립니다 ㅠㅠㅠ
환불 및 배송조회로 인한 불만이 야기되고 있어 이렇게 급하게 요청드리는점 양해부탁드립니다.

**Comment by shlee322** [comment]
처리되었습니다. 감사합니다.

**Comment by gaeun9188** [comment]
빠르게 처리해주셔서 정말 감사드립니다 ㅠㅠ !
어제 처리 되었다는 답변을 받고 잘 진행됐었는데,
오늘 동일 증상이 또 발생되어, 추후 해당오류가 또 발생될지 걱정이 앞서네요 ㅠㅠ
신경써주셔서 감사합니다! 문제 발생시 동일방법으로 연락드리겠습니다!  

+ 혹, 관련하여 오류원인을 알수있을까요? 아니면 처리가 되더라도 이문제가 자주 발생될 수 있는지 궁금합니다.
